// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Models;

namespace WebApplication.Migrations
{
    [DbContext(typeof(TranslationContext))]
    partial class TranslationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("WebApplication.Models.Translation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Chinese")
                        .HasColumnType("longtext");

                    b.Property<string>("English")
                        .HasColumnType("longtext");

                    b.Property<string>("Hungarian")
                        .HasColumnType("longtext");

                    b.Property<string>("Portuguese")
                        .HasColumnType("longtext");

                    b.Property<string>("Spanish")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
